spring.datasource.url=jdbc:sqlserver://servernote.database.windows.net:1433;database=noteBaza;user=NoteAdmin@servernote;password=Note1234;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.datasource.initialization-mode=always

